<?php

/**
 * @file
 */

/**
 * Update existing fields to move Entity Reference and Link settings out from
 * the contrib key.
 */
function textformatter_update_1100() {
  $changes = array(
    'entityreference_link',
    'link_field_display_type',
  );
  $field_instances = field_info_instances();
  foreach ($field_instances as $entity_type => $bundles) {
    if (!empty($bundles)) {
      foreach ($bundles as $bundle => $fields) {
        if (!empty($fields)) {
          foreach ($fields as $field_name => $field_instance) {
                  $pause = 1;
            foreach ($changes as $change) {
              if (!empty($field_instance['settings']['textformatter_contrib'][$change])) {
                $field_instance['settings']['textformatter_' . $change] = $field_instance['settings']['textformatter_contrib'][$change];
                unset($field_instance['settings']['textformatter_contrib'][$change]);
                field_update_instance($field_instance);
              }
            }
          }
        }
      }
    }
  }
}
